#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
PyQt5 GUI for MONTE CARLO TDC SIMULATION (tdc_jitter_sim_def.py)
----------------------------------------------------------------

REQUIREMENTS
------------
    - tdc_jitter_sim_def.py in the SAME folder as this file
    - Python 3 with numpy, matplotlib and PyQt5
    
    Use the following commands to install PyQt5:
          Ubuntu / WSL :  sudo apt install python3-pyqt5
          Windows      :  python -m pip install PyQt5

USAGE
-----
    python3 tdc_jitter_gui_def.py

"""

import contextlib
import datetime
import io
import os
import re
import sys
import tempfile
from timeit import default_timer as timer

# Make tdc_jitter_sim_def.py importable even if program is launched from a different folder
HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from PyQt5.QtWidgets import QApplication, QWidget, QSlider, QVBoxLayout
from PyQt5.QtWidgets import QMainWindow, QMessageBox, QScrollArea
from PyQt5.QtWidgets import QLabel, QHBoxLayout, QLineEdit, QFileDialog
from PyQt5.QtWidgets import QGridLayout, QCheckBox, QComboBox, QPushButton
from PyQt5.QtWidgets import QTabWidget, QTextEdit, QSizePolicy
from PyQt5.QtCore import Qt, pyqtSlot, QRunnable, QThreadPool, QObject, pyqtSignal
from PyQt5 import QtGui

import tdc_jitter_sim_def as sim


# Folder where output .txt file is written
SAVE_FOLDER = os.path.join(HERE, "Data_TDC")

# Allowed range (min, max) of values typed in text boxes
RANGES = {
    "f_clk_mhz":   (1.0, 5000.0),
    "sigma_rj":    (0.0, 200.0),
    "lsb":         (0.5, 500.0),
    "dcd_pp":      (0.0, 100.0),
    "pj_freq_mhz": (0.01, 1000.0),
    "n_events":    (1000, 2000000),
}

# Plain-language explanation shown under each parameter.
HINTS = dict(
    f_clk_mhz="Coarse counter reference clock frequency [MHz]. "
              "Sets the main time-stamp binning (t_clk = 1/f_clk_mhz).",
    sigma_rj="Random clock jitter RMS [ps]. Represents uncorrelated white phase noise "
             "on clock edge arrivals (0 = ideal clock).",
    lsb="Fine TAC quantization resolution [ps]. "
        "Sets the baseline RMS quantization error (LSB / sqrt(12)).",
    nearest="Edge selection mode: Rising-Edge only (immune to DCD) or "
            "Nearest Edge (uses both edges, subject to DCD effect).",
    dcd_pp="Duty-Cycle Distortion (DCD) peak-to-peak [ps]. Peak shift of falling edges "
           "from ideal 50% duty cycle (active only in Nearest Edge mode).",
    alpha_rw="Fraction of random walk jitter (0 = pure white noise, 1 = pure random-walk/correlated noise). "
             "Total RMS jitter budget remains fixed.",
    pj_amp="Peak amplitude of deterministic periodic jitter [ps]. "
           "Simulates periodic power supply switching or crosstalk interference (produces spectral spurs).",
    pj_freq_mhz="Frequency of the periodic jitter interference [MHz]. "
                "Active only when periodic jitter is enabled.",
    inl_amp="Peak Integral Non-Linearity (INL) distortion [ps]. "
            "Simulates systematic non-linear transfer curve defects in the fine TAC stage.",
    n_events="Number of simulated time measurements (Monte Carlo trials). "
            "Larger values provide higher statistical precision at the expense of increased run time.",
)

INTRO_TEXT = ("Configure the simulation parameters below. Available parameter ranges are indicated "
    "next to each field, with technical details provided in the hints below. "
    "Checkboxes enable or disable optional noise mechanisms. "
    "Click \"Run\" to start the simulation.")

RUN_HINT = ("Execution typically takes a few seconds. Upon completion, the "
    "analytical summary report and interactive plot windows will open automatically. "
    "Closing this main window will close all plot windows simultaneously. "
    "All outputs are saved to the 'Data_TDC' directory.")

# Plots generated by tdc_jitter_sim_def.main():
# (in order: file name, tab title and description under the plot)
PLOTS = [
    ("tdc_error_histogram.png", "Error distribution",
     "Empirical TDC error distribution (histogram) overlaid with the analytical "
     "Gaussian model (red dashed curve). Alignment between the histogram bars and the "
     "theoretical Root-Sum-Square (RSS) error model validates the simulation."),
    ("tdc_dither_effect.png", "Dither effect",
    "Demonstration of the dither effect across four fixed random jitter levels "
    "(0.5 ps, 2 ps, 7.11 ps, and 20 ps RMS). At low jitter, the error is dominated "
    "by fine-stage quantization, yielding an almost uniform 'blocky' distribution. "
    "Higher jitter levels smooth out quantization steps into a more Gaussian profile (dither effect). "
    "Note: jitter values for this plot are preset; all other system parameters reflect "
    "GUI inputs."),
    ("tdc_jitter_sweep.png", "Error vs jitter",
     "Evolution of total TDC measurement error (RMS) as clock jitter sweeps from 0.5 ps "
    "to 30 ps. Blue dots represent empirical Monte Carlo simulation results; the red dashed "
    "curve shows the theoretical RSS prediction. The gray dotted line marks the "
    "quantization noise floor (LSB / sqrt(12)), while the green vertical line indicates "
    "the currently selected clock jitter setting."),
    ("tdc_dcd_effect.png", "Duty cycle effect",
    "Comparative analysis of clock edge sampling modes under DCD. "
    "Left: Rising-Edge Mode, using only clock rising edges; the measurement is immune "
    "to DCD. Right: Nearest-Edge Mode, incorporating falling edges; DCD introduces "
    "asymmetry between alternating edges, splitting the error histogram into a bimodal "
    "distribution. Note: This plot displays both modes side-by-side for direct comparison, "
    "irrespectively of the mode selected in the main window."),
    ("tdc_error_spectrum.png", "Error spectrum",
    "Frequency spectrum (Fast-Fourier Transform) of the TDC measurement error sequence. "
    "Uncorrelated random jitter and quantization produce a flat broadband noise floor. "
    "A narrow discrete peak ('spectral spur') indicates deterministic periodic disturbances, "
    "such as periodic jitter or DCD in nearest-edge mode."),
]

REPORT_HELP = (
    "How to read this report:\n"
    "ANALYTICAL BUDGET presents the contribution of each individual error source "
    "(jitter, DCD, fine quantization) and the total predicted by the "
    "RSS error model (sigma_TOT). "
    "MONTE CARLO SIMULATION shows the empirical error obtained from simulated measurements "
    "(sigma_sim); it should closely match the RSS prediction ('dev. vs RSS' near 0%). "
    "CONFIDENCE INTERVALS indicate that a single measurement falls within +/- 1, 2, and 3 sigma "
    "of the true timestamp with probabilities of 68.3%, 95.4%, and 99.7% respectively. "
    "If Periodic Jitter or INL are enabled, they fall outside the standard Gaussian RSS budget, "
    "so sigma_sim is expected to exceed sigma_TOT."
)


def show_number(value):
    """Text within a box for parameters/modes configuration."""
    if isinstance(value, int):
        return str(value)
    return str(int(value)) if float(value).is_integer() else f"{value:g}"


def range_text(key):
    """Text next to a box describing available parameter range"""
    lo, hi = RANGES[key]
    return f"allowed: {show_number(lo)} to {show_number(hi)}"


def make_hint(text):
    """Short hints below text boxes."""
    label = QLabel(text)
    label.setWordWrap(True)
    font = label.font()
    font.setPointSize(8)
    label.setFont(font)
    label.setStyleSheet("color: #555555;")
    return label


class LabelTextedit(QWidget):
    """
    Text to change parameters of TDC simulation and number of events.
    Allowed values are shown next to text boxes, while field explanation appears below.
    """
    def __init__(self, label, hint, default=None, allowed=""):
        super().__init__()
        self.__initUi__(label, hint, default, allowed)

    def __initUi__(self, label, hint, default, allowed):

        self.__text_label = QLabel()
        self.__text_label.setText(label)
        self.__textbox = QLineEdit(self)
        if default is not None:
            self.__textbox.setText(default)     # starting value shown in the box
        my_font = self.__text_label.font()
        my_font.setPointSize(9)
        self.__text_label.setFont(my_font)
        self.__text_label.setAlignment(Qt.AlignCenter)

        # box + allowed range on the same line
        row = QHBoxLayout()
        row.addWidget(self.__textbox)
        row.addWidget(QLabel(allowed))

        lay = QVBoxLayout()

        lay.addWidget(self.__text_label)
        lay.addLayout(row)
        lay.addWidget(make_hint(hint))
        self.setLayout(lay)

    def update_variable_float(self):
        # Reads number written the __textbox (decimal comma is accepted).
        # If text is not a number, box is cleared and None is returned.
        try:
            variable = float(self.__textbox.text().replace(",", "."))
            return variable
        except ValueError:
            self.__textbox.clear()
            return None

    def update_variable_int(self):
        # Same for a whole number
        try:
            variable = int(self.__textbox.text())
            return variable
        except ValueError:
            self.__textbox.clear()
            return None


class LabelQcombo(QWidget):
    """
    Selector choosing clock edges utilized by fine measurement
    """
    def __init__(self, label, hint, list_of_elements):
        super().__init__()
        self.__initUi__(label, hint, list_of_elements)

    def __initUi__(self, label, hint, list_of_elements):

        self.__text_label = QLabel()
        self.__text_label.setText(label)
        my_font = self.__text_label.font()
        my_font.setPointSize(9)
        self.__text_label.setFont(my_font)
        self.__text_label.setAlignment(Qt.AlignCenter)
        self.__Combobox = QComboBox(self)
        self.__Combobox.addItems(list_of_elements)

        lay = QVBoxLayout()

        lay.addWidget(self.__text_label)
        lay.addWidget(self.__Combobox)
        lay.addWidget(make_hint(hint))
        self.setLayout(lay)

    def get_value(self):
        # Position of selected element in the list: 0 = first, 1 = second
        return self.__Combobox.currentIndex()


class WorkerSignals(QObject):
    '''
    Defines signals available from a running worker thread.

    Supported signals are:
    - started (data returned from starting process)
    - result (object data returned from processing)
    - completed (data returned from completed process)

    '''

    started = pyqtSignal(object)
    result = pyqtSignal(object)
    completed = pyqtSignal(object)


class Worker(QRunnable):
    '''
    Worker thread execution task.

    Inherits from QRunnable to offload heavy computations (e.g., Monte Carlo simulations)
    to a background thread, preventing main GUI from freezing. Communicates status 
    and results back to the GUI thread via a WorkerSignals object.
    '''

    def __init__(self, fn=None, *args, **kwargs):
        super(Worker, self).__init__()

        # Store constructor arguments (re-used for processing)
        self.fn = fn
        self.args = args
        self.kwargs = kwargs
        self.signals = WorkerSignals()

    @pyqtSlot()
    def run(self):
        self.signals.started.emit(self)
        result = self.fn(*self.args, **self.kwargs)
        self.signals.result.emit(result)
        self.signals.completed.emit(self)


class LabelSlider(QWidget):
    """
    Control widget for optional effects in the simulation.

    - Checkbox: toggles noise mechanism on or off. When unchecked, parameter value defaults to 0.
    - Slider: controls normalized integer step (0 to 20). Enabled only when checkbox is checked.
    - Value Scaling: converts slider position to physical parameter value (Value = Position × Scale).
    - Layout: Displays allowed physical range adjacent to the slider alongside an explanation below.

    """
    def __init__(self, label, hint, allowed, scale=1, decimals=0):
        super().__init__()
        self.__scale = scale
        self.__decimals = decimals
        self.__initUi__(label, hint, allowed)

    def __initUi__(self, label, hint, allowed):

        self.__check = QCheckBox()

        self.__text_label = QLabel(label)
        self.__text_label.setText(label)
        my_font = self.__text_label.font()
        my_font.setPointSize(9)
        self.__text_label.setFont(my_font)

        Label_layout = QHBoxLayout()
        Label_layout.setAlignment(Qt.AlignLeft)
        Label_layout.addWidget(self.__check)
        Label_layout.addWidget(self.__text_label)

        self.__slider_value = 0
        self.__slider = QSlider()
        self.__slider.setOrientation(Qt.Horizontal)
        self.__slider.setRange(0, 20)        # default range
        self.__slider.setValue(self.__slider_value)
        self.__slider.valueChanged.connect(self.__valueChanged)
        self.__slider.setSingleStep(1)
        self.__slider.setEnabled(False)

        self.__check.stateChanged.connect(self.toggle_slider)

        self.__zoomLabel = QLabel()
        self.__zoomLabel.setText(self.__shown_text(self.__slider_value))
        self.__zoomLabel.setFixedWidth(self.__zoomLabel.fontMetrics().boundingRect(self.__zoomLabel.text()).width() + 5)

        layout = QVBoxLayout()
        lay_slider = QHBoxLayout()
        lay_slider.setAlignment(Qt.AlignRight | Qt.AlignVCenter)
        lay_slider.addWidget(self.__zoomLabel, Qt.AlignLeft)
        lay_slider.addWidget(self.__slider, Qt.AlignLeft)
        lay_slider.addWidget(QLabel(allowed))
        layout.addLayout(Label_layout)
        layout.addLayout(lay_slider)
        layout.addWidget(make_hint(hint))

        self.setLayout(layout)

    def __shown_text(self, position):
        return f"{position * self.__scale:.{self.__decimals}f}"

    def __valueChanged(self, v):
        self.__zoomLabel.setText(self.__shown_text(v))
        self.__zoomLabel.setFixedWidth(self.__zoomLabel.fontMetrics().boundingRect(
                                         self.__zoomLabel.text()).width() + 5)

    def slider_change(self):
        # Effect-associated value: 0 if the check box is not ticked
        if not self.__check.isChecked():
            return 0.0
        return float(self.__slider.value()) * self.__scale

    def toggle_slider(self, checked):
        # Toggle slider enabled state
        self.__slider.setEnabled(bool(checked))

    def preset(self, checked, position):
        # Check box and the slider starting value/state
        self.__slider.setValue(position)
        self.__check.setChecked(checked)

    def getLabel(self):
        return self.__zoomLabel

    def getSlider(self):
        return self.__slider

    def getSlidervalue(self):
        return self.__slider_value


class PlotPage(QWidget):
    """
    Single-plot window: plot is resized to fit the window; under the plot, 
    the relative description/explanation
    """
    def __init__(self, file_name, explanation):
        super().__init__()
        self.file_name = file_name
        self.raw = None             # bytes of the PNG file
        self.pixmap = None          # same image as whown by Qt

        # Resizing ignored: the image follows the window size instead of
        # forcing the window to the size of the image.
        self.image_label = QLabel("No plot yet.")
        self.image_label.setAlignment(Qt.AlignCenter)
        self.image_label.setSizePolicy(QSizePolicy.Ignored, QSizePolicy.Ignored)
        self.image_label.setMinimumSize(1, 1)

        explain = QLabel(explanation)
        explain.setWordWrap(True)
        save_button = QPushButton("Save image...")
        save_button.clicked.connect(self.save)

        bottom = QHBoxLayout()
        bottom.addWidget(explain, 1)
        bottom.addWidget(save_button, 0, Qt.AlignTop)

        lay = QVBoxLayout(self)
        lay.addWidget(self.image_label, 1)
        lay.addLayout(bottom)

    def set_image(self, raw_bytes):
        self.raw = raw_bytes
        if raw_bytes is None:
            self.pixmap = None
            self.image_label.setText("Image not available.")
            return
        pixmap = QtGui.QPixmap()
        pixmap.loadFromData(raw_bytes, "PNG")
        self.pixmap = pixmap
        self._rescale()

    def _rescale(self):
        if self.pixmap is None or self.pixmap.isNull():
            return
        # Shrink to fit the available area, never enlarge beyond the original.
        size = self.image_label.size().boundedTo(self.pixmap.size())
        self.image_label.setPixmap(self.pixmap.scaled(
            size, Qt.KeepAspectRatio, Qt.SmoothTransformation))

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self._rescale()

    def save(self):
        if self.raw is None:
            QMessageBox.information(self, "Nothing to save", "Run the simulation first.")
            return
        path, _ = QFileDialog.getSaveFileName(self, "Save image", self.file_name,
                                              "PNG image (*.png)")
        if path:
            with open(path, "wb") as f:
                f.write(self.raw)


class ReportWindow(QWidget):
    """
    Numerical Report Window, introduced by a short guide describing how to
    read it (Each plot has its own window)
    """
    def __init__(self):
        super().__init__()
        self.setWindowTitle("TDC Jitter Simulator - Numerical Report")
        self.resize(820, 560)

        help_label = QLabel(REPORT_HELP)
        help_label.setWordWrap(True)
        self.report_box = QTextEdit()
        self.report_box.setReadOnly(True)
        self.report_box.setLineWrapMode(QTextEdit.NoWrap)
        self.report_box.setFont(QtGui.QFontDatabase.systemFont(QtGui.QFontDatabase.FixedFont))

        lay = QVBoxLayout(self)
        lay.addWidget(help_label)
        lay.addWidget(self.report_box, 1)

    def update_results(self, report):
        """Show report of last run."""
        self.report_box.setPlainText(report)


class my_window(QMainWindow):
    """
    Window for TDC Jitter Simulator (uses all previous classes to build Main window)
    """
    def __init__(self, *args, **kwargs):
        super(my_window, self).__init__()
        self.report_window = None       # window with the numerical report
        self.plot_windows = {}          # one window for each plot
        self.__initUi__(self, *args, **kwargs)

    def __initUi__(self, *args, **kwargs):

        # The text boxes start with the default values of tdc_jitter_sim_def.py
        self.f_clk = LabelTextedit("Clock frequency \n(MHz)", HINTS["f_clk_mhz"],
                                   show_number(sim.F_CLK / 1e6), range_text("f_clk_mhz"))
        self.sigma_rj = LabelTextedit("Random clock jitter \n(ps)", HINTS["sigma_rj"],
                                      show_number(sim.SIGMA_RJ), range_text("sigma_rj"))
        self.lsb = LabelTextedit("TAC resolution (LSB) \n(ps)", HINTS["lsb"],
                                 show_number(sim.LSB), range_text("lsb"))
        self.edge_selector = LabelQcombo("Clock edges used", HINTS["nearest"],
                                         ["Rising edge only", "Nearest edge (rising or falling)"])
        self.dcd = LabelTextedit("Duty cycle distortion \n(ps)", HINTS["dcd_pp"],
                                 show_number(sim.DCD_PP), range_text("dcd_pp"))
        self.slider_rw = LabelSlider("Random-walk share of jitter", HINTS["alpha_rw"],
                                     "0 to 1", 0.05, 2)
        self.slider_pj = LabelSlider("Periodic jitter amplitude (ps)", HINTS["pj_amp"],
                                     "0 to 20 ps")
        self.slider_inl = LabelSlider("TAC non-linearity, INL (ps)", HINTS["inl_amp"],
                                      "0 to 20 ps")
        self.pj_freq = LabelTextedit("Periodic jitter frequency \n(MHz)", HINTS["pj_freq_mhz"],
                                     show_number(sim.PJ_FREQ / 1e6), range_text("pj_freq_mhz"))
        self.N_events = LabelTextedit("Number of events \n(integer)", HINTS["n_events"],
                                      show_number(sim.N_EVENTS), range_text("n_events"))
        self.runButton = QPushButton()
        self.runButton.setText("Run")
        self.runButton.setFixedWidth(100)

        # Sliders initial state (imported from tdc_jitter_sim_def.py)
        self.slider_rw.preset(sim.ALPHA_RW > 0, int(round(sim.ALPHA_RW / 0.05)))
        self.slider_pj.preset(sim.PJ_AMP > 0, int(round(sim.PJ_AMP)))
        self.slider_inl.preset(sim.INL_AMP > 0, int(round(sim.INL_AMP)))

        intro = QLabel(INTRO_TEXT)
        intro.setWordWrap(True)

        central_widget = QWidget(self)
        layout = QGridLayout(central_widget)
        layout.addWidget(intro, 0, 0, 1, 3)
        layout.addWidget(self.f_clk, 1, 0)
        layout.addWidget(self.sigma_rj, 2, 0)
        layout.addWidget(self.lsb, 3, 0)
        layout.addWidget(self.edge_selector, 4, 0)
        layout.addWidget(self.dcd, 5, 0)
        layout.addWidget(self.slider_rw, 1, 1)
        layout.addWidget(self.slider_pj, 2, 1)
        layout.addWidget(self.slider_inl, 3, 1)
        layout.addWidget(self.pj_freq, 4, 1)
        layout.addWidget(self.N_events, 1, 2)
        layout.addWidget(self.runButton, 2, 2, Qt.AlignCenter)
        layout.addWidget(make_hint(RUN_HINT), 3, 2, Qt.AlignTop)
        layout.setRowStretch(6, 1)

        # The grid is placed in a scroll area, so that the window can also be
        # smaller than its content (small screens).
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setWidget(central_widget)

        logo = os.path.join(HERE, "TDC_logo.png")      # optional
        if os.path.exists(logo):
            self.setWindowIcon(QtGui.QIcon(logo))
        self.setWindowTitle('TDC Jitter Simulator')
        self.setGeometry(150, 80, 1100, 760)
        self.setCentralWidget(scroll)
        # Function connected to the Run button
        self.runButton.clicked.connect(self.thread_work)
        self.show()

    def message_box(self, values):
        """
        Called in the main thread, because windows can only be created there.
        It uses output values from the Worker to open report window + one
        window for each of the 5 plots (alongside its explanation).
        A bool variable is set to generate a Qmessagebox in case of
        wrong set of parameters or failed simulation.

        """
        enable = values[1]

        if(not enable):
            dlg = QMessageBox()
            dlg.setWindowIcon(self.windowIcon())
            dlg.setWindowTitle("Error")
            dlg.setText(values[0])
            dlg.exec()
            self.runButton.setText("Run")
            self.runButton.setEnabled(True)
        else:

            print("Filling the output plots ...")
            start = timer()
            images = values[2]
            report = values[4]

            if self.report_window is None:
                self.report_window = ReportWindow()
            self.report_window.update_results(report)
            self.report_window.show()
            self.report_window.raise_()

            # One window for each plot. The windows are created, then reused 
            #afterwards; placed one after the other, slightly shifted
            for index, (file_name, title, explanation) in enumerate(PLOTS):
                if file_name not in self.plot_windows:
                    page = PlotPage(file_name, explanation)
                    page.setWindowTitle("TDC Jitter Simulator - " + title)
                    page.resize(900, 550)
                    page.move(80 + 40 * index, 60 + 40 * index)
                    self.plot_windows[file_name] = page
                page = self.plot_windows[file_name]
                page.set_image(images.get(file_name))
                page.show()
                page.raise_()

            end = timer()
            print("## PLOTS PRINTED AFTER: " + str(round(end - start, 3)) + " s ##\n")

            start_process = values[3]
            end_process = timer()

            print("## PROCESS COMPLETED AFTER: " + str(round(end_process - start_process, 3)) + " s ##\n")
            # Main window stays open, so that a new run can start
            self.runButton.setText("Run")
            self.runButton.setEnabled(True)

    def closeEvent(self, event):
        # Closing main window also closes the others
        if self.report_window is not None:
            self.report_window.close()
        for page in self.plot_windows.values():
            page.close()
        event.accept()

    def thread_work(self):
        # Pass the function to a Worker object for execution, with the variables list values set in the application

        self.runButton.setText("Running...")
        variables = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
        variables[0] = self.f_clk.update_variable_float()
        variables[1] = self.sigma_rj.update_variable_float()
        variables[2] = self.lsb.update_variable_float()
        variables[3] = self.edge_selector.get_value()
        variables[4] = self.dcd.update_variable_float()
        variables[5] = self.pj_freq.update_variable_float()
        variables[6] = self.slider_rw.slider_change()
        variables[7] = self.slider_pj.slider_change()
        variables[8] = self.slider_inl.slider_change()
        variables[9] = self.N_events.update_variable_int()

        pool = QThreadPool.globalInstance()
        worker = Worker(lambda: self.button_clicked(variables)) 
        self.runButton.setEnabled(False)
        worker.signals.result.connect(self.message_box)
        pool.start(worker)

    def check_range(self, name, value, key):
        # Returns an error line if 'value' is missing or outside allowed range
        lo, hi = RANGES[key]
        if value is None or not (lo <= value <= hi):
            return f"-{name} must be a number between {show_number(lo)} and {show_number(hi)}-\n"
        return ""

    def button_clicked(self, variables):
        """
        Main function setting selected data for simulation.
        It copies user settings into tdc_jitter_sim_def, runs it, writes output file
        and returns report and images
        """

        f_clk = variables[0]
        sigma_rj = variables[1]
        lsb = variables[2]
        edge_mode = variables[3]
        dcd = variables[4]
        pj_freq = variables[5]
        alpha_rw = variables[6]
        pj_amp = variables[7]
        inl_amp = variables[8]
        n_events = variables[9]

        message = ""
        message += self.check_range("Clock frequency", f_clk, "f_clk_mhz")
        message += self.check_range("Random clock jitter", sigma_rj, "sigma_rj")
        message += self.check_range("TAC resolution (LSB)", lsb, "lsb")
        message += self.check_range("Duty cycle distortion", dcd, "dcd_pp")
        message += self.check_range("Periodic jitter frequency", pj_freq, "pj_freq_mhz")
        message += self.check_range("Number of events (whole number)", n_events, "n_events")

        if(message != ""):
            # enable signal for correct setting of all the parameters
            return [message.strip(), False]

        else:
            Process_start = timer()
            print("\n## PROCESS RUNNING ##\n")

            # Names on the left are the ones of the PARAMETERS block of
            # tdc_jitter_sim_def.py. Frequencies set in MHz, here are converted in Hz.
            sim.F_CLK = f_clk * 1e6
            sim.T_CLK = 1e12 / sim.F_CLK            # same formula as in the original file
            sim.SIGMA_RJ = sigma_rj
            sim.LSB = lsb
            sim.USE_NEAREST_EDGE = (edge_mode == 1)
            sim.DCD_PP = dcd
            sim.PJ_FREQ = pj_freq * 1e6
            sim.ALPHA_RW = alpha_rw
            sim.PJ_AMP = pj_amp
            sim.INL_AMP = inl_amp
            sim.N_EVENTS = n_events

            # TDC simulation
            print("Simulation processing ...")
            start = timer()
            old_outdir = sim.OUTDIR
            printed = io.StringIO()
            images = {}
            try:
                with tempfile.TemporaryDirectory() as folder:
                    sim.OUTDIR = folder
                    # everything the simulation prints is captured, then shown
                    with contextlib.redirect_stdout(printed):
                        sim.main()
                    for file_name, title, explanation in PLOTS:
                        path = os.path.join(folder, file_name)
                        if os.path.exists(path):
                            with open(path, "rb") as f:
                                images[file_name] = f.read()
            except Exception as error:
                print("## PROCESS FAILED: " + str(error) + " ## \n")
                return ["The simulation failed: " + str(error), False]
            finally:
                sim.OUTDIR = old_outdir
            end = timer()
            print("## TDC SIMULATION COMPLETED AFTER: " + str(round(end - start, 3)) + " s ##\n")

            # numerical report 
            report = re.sub(r"\n*Plots saved in:.*\s*$", "", printed.getvalue())
            print(report + "\n")

            print("Writing the output file...")
            # generate output .txt file with all final results
            now = datetime.datetime.now()
            d_h_format = now.strftime("%Y-%m-%d_%H-%M-%S")
            file_title = os.path.join(SAVE_FOLDER, f"TDC_Simulator_Data_{d_h_format}.txt")

            string_list = []
            string_list.append(f"********TDC_Simulator_Data_{d_h_format}********\n")
            string_list.append("Clock frequency: " + show_number(f_clk) + " MHz\n")
            string_list.append("Random clock jitter (sigma_RJ): " + show_number(sigma_rj) + " ps\n")
            string_list.append("Random-walk share of jitter: " + show_number(round(alpha_rw, 4)) + "\n")
            string_list.append("TAC resolution (LSB): " + show_number(lsb) + " ps\n")
            string_list.append("Clock edges used: " + ("nearest edge (rising or falling)" if edge_mode == 1 else "rising edge only") + "\n")
            string_list.append("Duty cycle distortion (DCD): " + show_number(dcd) + " ps\n")
            if pj_amp != 0:
                string_list.append("Periodic jitter amplitude: " + show_number(pj_amp) + " ps\n")
                string_list.append("Periodic jitter frequency: " + show_number(pj_freq) + " MHz\n")
            else:
                string_list.append("Periodic jitter: off\n")
            if inl_amp != 0:
                string_list.append("TAC non-linearity (INL): " + show_number(inl_amp) + " ps\n")
            else:
                string_list.append("TAC non-linearity (INL): off\n")
            string_list.append("Number of events: " + str(n_events) + "\n")
            string_list.append("\nResults:\n" + report.rstrip() + "\n")

            data_file = ""
            for string in string_list:
                data_file += string

            try:
                os.makedirs(SAVE_FOLDER, exist_ok=True)     # create the folder if it does not exist
                with open(file_title, 'w', encoding="utf-8") as file:
                    file.write(data_file)

                print(f"## DATA WRITTEN IN: {file_title}  ## \n")
            except OSError:
                print("## PROCESS FAILED: could not write in the Data_TDC folder! ## \n")
                return ["Could not write in the Data_TDC folder!", False]

            return [" ", True, images, Process_start, report]


if __name__ == '__main__':

    app = QApplication(sys.argv)
    window = my_window()
    window.show()
    sys.exit(app.exec_())
